function constraint = f_friction_2DSS(in1)
%F_FRICTION_2DSS
%    CONSTRAINT = F_FRICTION_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    26-Jan-2017 16:45:14

F1 = in1(:,1);
F2 = in1(:,2);
constraint = abs(F1)./F2;
