function constraint = f_GRF_2DSS(in1)
%F_GRF_2DSS
%    CONSTRAINT = F_GRF_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    30-Jan-2017 22:04:50

F2 = in1(:,2);
constraint = F2;
