function constraint = f_GRF_2DSS(in1)
%F_GRF_2DSS
%    CONSTRAINT = F_GRF_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    26-Jan-2017 16:45:14

F2 = in1(:,2);
constraint = F2;
