function constraint = f_hInit_2DSS(in1)
%F_HINIT_2DSS
%    CONSTRAINT = F_HINIT_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    30-Jan-2017 22:04:41

h1 = in1(:,1);
h2 = in1(:,2);
constraint = [h1;h2];
