function constraint = f_hInit_2DSS(in1)
%F_HINIT_2DSS
%    CONSTRAINT = F_HINIT_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    11-Nov-2016 17:10:40

h1 = in1(:,1);
h2 = in1(:,2);
constraint = [h1;h2];
