function constraint = f_holonomicAcc_2DSS(in1)
%F_HOLONOMICACC_2DSS
%    CONSTRAINT = F_HOLONOMICACC_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    26-Jan-2017 16:44:59

ddq1 = in1(:,19);
ddq2 = in1(:,20);
ddq3 = in1(:,21);
ddq4 = in1(:,22);
ddq5 = in1(:,23);
dq1R = in1(:,13);
dq2R = in1(:,14);
dqT = in1(:,12);
q1R = in1(:,4);
q2R = in1(:,5);
qT = in1(:,3);
t2 = q1R+qT;
t3 = sin(t2);
t4 = q2R+qT;
t5 = sin(t4);
t6 = dq1R.*t3.*(1.0./2.0);
t7 = dq2R.*t5.*(1.0./2.0);
t8 = cos(t2);
t9 = cos(t4);
t10 = t8.*(1.0./2.0);
t11 = t9.*(1.0./2.0);
t12 = t10+t11;
t13 = t3.*(1.0./2.0);
t14 = t5.*(1.0./2.0);
t15 = t13+t14;
t16 = dq1R.*t8.*(1.0./2.0);
t17 = dq2R.*t9.*(1.0./2.0);
constraint = [ddq1-ddq4.*t8.*(1.0./2.0)-ddq5.*t9.*(1.0./2.0)-ddq3.*t12+dqT.*(t6+t7+dqT.*t15)+dq1R.*(t6+dqT.*t3.*(1.0./2.0))+dq2R.*(t7+dqT.*t5.*(1.0./2.0));ddq2-ddq4.*t3.*(1.0./2.0)-ddq5.*t5.*(1.0./2.0)-ddq3.*t15-dqT.*(t16+t17+dqT.*t12)-dq1R.*(t16+dqT.*t8.*(1.0./2.0))-dq2R.*(t17+dqT.*t9.*(1.0./2.0))];
