function constraint = f_holonomicPos_2DSS(in1)
%F_HOLONOMICPOS_2DSS
%    CONSTRAINT = F_HOLONOMICPOS_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Jan-2017 17:00:00

h1 = in1(:,10);
h2 = in1(:,11);
yLeg = in1(:,1);
zLeg = in1(:,2);
constraint = [-h1+yLeg;-h2+zLeg];
