function constraint = f_holonomicAcc_2DSS(in1)
%F_HOLONOMICACC_2DSS
%    CONSTRAINT = F_HOLONOMICACC_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Jan-2017 16:59:59

ddq1 = in1(:,19);
ddq2 = in1(:,20);
constraint = [ddq1;ddq2];
