function constraint = f_speed_2DSS(in1)
%F_SPEED_2DSS
%    CONSTRAINT = F_SPEED_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Jan-2017 17:00:19

T = in1(:,1);
q1L = in1(:,7);
q2L = in1(:,8);
q1R = in1(:,5);
q2R = in1(:,6);
qT = in1(:,4);
yLeg = in1(:,2);
constraint = (yLeg-sin(q1L+qT).*(1.0./2.0)-sin(q2L+qT).*(1.0./2.0)+sin(q1R+qT).*(1.0./2.0)+sin(q2R+qT).*(1.0./2.0))./T;
