function constraint = f_steplength_2DSS(in1)
%F_STEPLENGTH_2DSS
%    CONSTRAINT = F_STEPLENGTH_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Jan-2017 17:00:19

q1L = in1(:,6);
q2L = in1(:,7);
q1R = in1(:,4);
q2R = in1(:,5);
qT = in1(:,3);
yLeg = in1(:,1);
constraint = yLeg-sin(q1L+qT).*(1.0./2.0)-sin(q2L+qT).*(1.0./2.0)+sin(q1R+qT).*(1.0./2.0)+sin(q2R+qT).*(1.0./2.0);
