function constraint = f_swingFoot_guard_2DSS(in1)
%F_SWINGFOOT_GUARD_2DSS
%    CONSTRAINT = F_SWINGFOOT_GUARD_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Jan-2017 17:00:00

q1L = in1(:,6);
q2L = in1(:,7);
q1R = in1(:,4);
q2R = in1(:,5);
qT = in1(:,3);
zLeg = in1(:,2);
constraint = zLeg+cos(q1L+qT).*(1.0./2.0)+cos(q2L+qT).*(1.0./2.0)-cos(q1R+qT).*(1.0./2.0)-cos(q2R+qT).*(1.0./2.0);
