function constraint = f_timeCont_2DSS(in1)
%F_TIMECONT_2DSS
%    CONSTRAINT = F_TIMECONT_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    26-Jan-2017 16:45:12

T1 = in1(:,1);
T2 = in1(:,2);
constraint = T1-T2;
