function constraint = f_torso_2DSS(in1)
%F_TORSO_2DSS
%    CONSTRAINT = F_TORSO_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    11-Nov-2016 17:10:50

qT = in1(:,3);
constraint = qT;
