function J_constraint = J_GRF_2DSS(in1)
%J_GRF_2DSS
%    J_CONSTRAINT = J_GRF_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Jan-2017 17:55:19

J_constraint = [0.0,1.0];
