function J_constraint = J_hCont_2DSS(in1)
%J_HCONT_2DSS
%    J_CONSTRAINT = J_HCONT_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    30-Jan-2017 22:04:50

J_constraint = reshape([1.0,0.0,0.0,1.0,-1.0,0.0,0.0,-1.0],[2,4]);
