function J_constraint = J_hInit_2DSS(in1)
%J_HINIT_2DSS
%    J_CONSTRAINT = J_HINIT_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    30-Jan-2017 22:04:41

J_constraint = reshape([1.0,0.0,0.0,1.0],[2,2]);
