function J_constraint = J_kneeAngles_2DSS(in1)
%J_KNEEANGLES_2DSS
%    J_CONSTRAINT = J_KNEEANGLES_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    11-Nov-2016 17:10:48

J_constraint = reshape([0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,1.0,0.0,0.0,-1.0,0.0,1.0],[2,7]);
