function J_constraint = J_speed_2DSS(in1)
%J_SPEED_2DSS
%    J_CONSTRAINT = J_SPEED_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Jan-2017 17:00:19

T = in1(:,1);
q1L = in1(:,7);
q2L = in1(:,8);
q1R = in1(:,5);
q2R = in1(:,6);
qT = in1(:,4);
yLeg = in1(:,2);
t2 = 1.0./T;
t3 = q1L+qT;
t4 = q2L+qT;
t5 = q1R+qT;
t6 = q2R+qT;
t7 = cos(t5);
t8 = cos(t6);
t9 = cos(t3);
t10 = cos(t4);
J_constraint = [-1.0./T.^2.*(yLeg-sin(t3).*(1.0./2.0)-sin(t4).*(1.0./2.0)+sin(t5).*(1.0./2.0)+sin(t6).*(1.0./2.0)),t2,0.0,t2.*(t7.*(1.0./2.0)+t8.*(1.0./2.0)-t9.*(1.0./2.0)-t10.*(1.0./2.0)),t2.*t7.*(1.0./2.0),t2.*t8.*(1.0./2.0),t2.*t9.*(-1.0./2.0),t2.*t10.*(-1.0./2.0),0.0,0.0];
