function J_constraint = J_steplength_2DSS(in1)
%J_STEPLENGTH_2DSS
%    J_CONSTRAINT = J_STEPLENGTH_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Jan-2017 17:00:19

q1L = in1(:,6);
q2L = in1(:,7);
q1R = in1(:,4);
q2R = in1(:,5);
qT = in1(:,3);
t2 = q1R+qT;
t3 = cos(t2);
t4 = t3.*(1.0./2.0);
t5 = q2R+qT;
t6 = cos(t5);
t7 = t6.*(1.0./2.0);
t8 = q1L+qT;
t9 = cos(t8);
t10 = q2L+qT;
t11 = cos(t10);
J_constraint = [1.0,0.0,t4+t7-t9.*(1.0./2.0)-t11.*(1.0./2.0),t4,t7,t9.*(-1.0./2.0),t11.*(-1.0./2.0),0.0,0.0];
