function J_constraint = J_swingLegRetraction_2DSS(in1)
%J_SWINGLEGRETRACTION_2DSS
%    J_CONSTRAINT = J_SWINGLEGRETRACTION_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    11-Nov-2016 17:10:49

J_constraint = [0.0,0.0,0.0,1.0./2.0,1.0./2.0,0.0,0.0];
