function J_constraint = J_timeCont_2DSS(in1)
%J_TIMECONT_2DSS
%    J_CONSTRAINT = J_TIMECONT_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Jan-2017 17:55:18

J_constraint = [1.0,-1.0];
