function J_cost = J_torquePerSteplengthCost_2DSS(in1)
%J_TORQUEPERSTEPLENGTHCOST_2DSS
%    J_COST = J_TORQUEPERSTEPLENGTHCOST_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Jan-2017 17:00:20

q1L = in1(:,6);
q2L = in1(:,7);
q1R = in1(:,4);
q2R = in1(:,5);
qT = in1(:,3);
u1 = in1(:,10);
u2 = in1(:,11);
u3 = in1(:,12);
u4 = in1(:,13);
yLeg = in1(:,1);
t2 = q1L+qT;
t3 = sin(t2);
t4 = q2L+qT;
t5 = sin(t4);
t6 = q1R+qT;
t7 = sin(t6);
t8 = t7.*(1.0./2.0);
t9 = q2R+qT;
t10 = sin(t9);
t11 = t10.*(1.0./2.0);
t17 = t3.*(1.0./2.0);
t18 = t5.*(1.0./2.0);
t12 = t8+t11-t17-t18+yLeg;
t13 = abs(u1);
t14 = abs(u2);
t15 = abs(u3);
t16 = abs(u4);
t19 = abs(t12);
t20 = 1.0./t19.^2;
t21 = sign(t12);
t22 = t13.^2;
t23 = t14.^2;
t24 = t15.^2;
t25 = t16.^2;
t26 = t22+t23+t24+t25;
t27 = sqrt(t26);
t28 = cos(t6);
t29 = cos(t9);
t30 = cos(t2);
t31 = cos(t4);
t32 = 1.0./t19;
t33 = 1.0./sqrt(t26);
J_cost = [-t20.*t21.*t27,0.0,-t20.*t21.*t27.*(t28.*(1.0./2.0)+t29.*(1.0./2.0)-t30.*(1.0./2.0)-t31.*(1.0./2.0)),t20.*t21.*t27.*t28.*(-1.0./2.0),t20.*t21.*t27.*t29.*(-1.0./2.0),t20.*t21.*t27.*t30.*(1.0./2.0),t20.*t21.*t27.*t31.*(1.0./2.0),0.0,0.0,t13.*t32.*t33.*sign(u1),t14.*t32.*t33.*sign(u2),t15.*t32.*t33.*sign(u3),t16.*t32.*t33.*sign(u4)];
