function J_constraint = J_torso_2DSS(in1)
%J_TORSO_2DSS
%    J_CONSTRAINT = J_TORSO_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    11-Nov-2016 17:10:50

J_constraint = [0.0,0.0,1.0,0.0,0.0,0.0,0.0];
